name = "satyam-gold"
main = "functions/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = ""

[[d1_databases]]
binding = "DB"
database_name = "satyam-gold-production"
database_id = "c849a4c2-e7a8-47eb-acf1-77fc6276b0fd"

[[kv_namespaces]]
binding = "KV"
id = "your-kv-id-here"
preview_id = "your-kv-preview-id-here"

[[r2_buckets]]
binding = "R2"
bucket_name = "satyam-gold-images"

[vars]
ENVIRONMENT = "production"